# Generated by Django 4.1.3 on 2022-11-02 03:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('created', models.DateTimeField(default=datetime.datetime(2022, 11, 2, 3, 42, 47, 745784, tzinfo=datetime.timezone.utc))),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
